name: shop
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.7.0
  firebase_database: ^8.0.0
  firebase_auth: ^3.1.2
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.1
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.8
  splash_screen_view: ^3.0.0
  sqflite: ^2.0.0+4
  intl: ^0.17.0
  # conditional_builder: ^1.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  dio: ^4.0.0
  hexcolor: ^2.0.5
  webview_flutter: ^2.1.1
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700